services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: accounting
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  superset:
    build:
      context: .
      dockerfile: superset.Dockerfile
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "secret_key"
      SUPERSET_CONFIG_PATH: "/app/superset_home/superset_config.py"
    volumes:
      - superset_home:/app/superset_home
      - ./backend/superset_config.py:/app/superset_home/superset_config.py
    ports:
      - "8088:8088"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend/api/
      dockerfile: ../Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend/api/:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  minio_data:
  superset_home:
  pgadmin_data:
