# Generated by Django 5.1.4 on 2024-12-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='filepath',
        ),
    ]
