# Generated by Django 5.1.4 on 2024-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_invoice_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
