# Generated by Django 5.1.4 on 2024-12-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_invoice_invoice_file_invoice_invoice_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_url',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file',
            field=models.ImageField(default='123', upload_to='invoices/'),
            preserve_default=False,
        ),
    ]
