# Generated by Django 5.1.4 on 2025-02-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_invoice_invoice_url_invoice_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file',
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice')),
            ],
        ),
    ]
