# Generated by Django 5.1.4 on 2025-02-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_invoice_invoice_file_invoicefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_file',
            field=models.ImageField(default='', upload_to='invoices/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvoiceFile',
        ),
    ]
