# Generated by Django 5.1.4 on 2025-02-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_invoice_invoice_file_upload_invoice_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
    ]
