# Generated by Django 5.1.4 on 2025-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_remove_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
