# Generated by Django 5.1.4 on 2025-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_invoice_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
